spring:
  minio:
    url: https://play.min.io
    accessKey: Q3AM3UQ867SPQQA43P2F
    secretKey: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
    # not required
    region:
    endpoint:
      enable: true
      name: minio